name: Lint Backend

on: [push, pull_request]

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    name: Lint JAVA
    steps:
      - uses: actions/checkout@v3

      - name: Set up JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Download checkstyle
        run: curl -L -o checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.1/checkstyle-10.12.1-all.jar

      - name: Run checkstyle
        run: |
          java -jar checkstyle.jar -c /google_checks.xml app/src/main/java/com/project/back_end || true